### ISSUE TITLE
Scala3 migration

### ISSUE THREAD

**Issue by NicolasRouquette** [fprime-community/fpp#120]
Since the source code compiles with Scala 2.13, it makes sense to begin a gentle migration to Scala 3.
From my personal experience, there are a few compelling reasons to do this:
- The new braceless syntax definitely helps w.r.t conciseness.
- The compiler error messages have been improved, which is always helpful.
- The replacement of implicits with `given` and `using` is also a significant improvement.

The plan is to do the minimum necessary to get the code to compile w/ Scala3 and pass all unit tests.

**Comment by NicolasRouquette** [comment]
WIP: https://github.com/fprime-community/fpp/pull/121

**Comment by NicolasRouquette** [comment]
After this PR, I will try this Scala3 migration tool: https://docs.scala-lang.org/scala3/guides/migration/scala3-migrate.html

**Comment by bocchino** [comment]
Done in #122.
