### ISSUE TITLE
Link to Language Specification in FPP Wiki redirects to 404 page

### ISSUE THREAD

**Issue by capsulecorplab** [fprime-community/fpp#155]
[Language Specification](https://fprime-community.github.io/fpp/fpp/fpp-spec.html) link under [Primarily for Implementers](https://github.com/fprime-community/fpp/wiki#primarily-for-implementers) section in the [fpp wiki](https://github.com/fprime-community/fpp/wiki) redirects to 404 page

**Comment by bocchino** [comment]
Good catch, thanks! Fixed.
