### ISSUE TITLE
failed to install via pip

### ISSUE THREAD

**Issue by sayaplayer96** [fprime-community/fpp#164]
Hi, when i try to install fprime-fpp by the following command (on a Raspberry 4B with Raspbian)
pip install fprime-fpp
i got the following error message:
      -- WARN  -- Failed to retrieve https://github.com/fprime-community/fpp/releases/download/v1.0.2/native-fpp-Linux-aarch64.tar.gz with error: HTTP Error 404: Not Found
there is only "native-fpp-Linux-x86_64.tar.gz" in the 1.0.2 release, not "native-fpp-Linux-aarch64.tar.gz"
Could you please tell me how to fix this problem? thx:)

**Comment by sayaplayer96** [comment]
Then I switch to offline installation, changed the "artifact_string" in fprime_fpp/fprime_fpp_install.py to native-fpp-Linux-x86_64.tar.gz and use python setup.py install command.
I got another error msg:
-- INFO  -- Fetching FPP tools at https://github.com/fprime-community/fpp/releases/download/v1.0.2/native-fpp-Linux-x86_64.tar.gz
-- ERROR -- Failed find expected download: [Errno 8] Exec format error: '/tmp/__FPP_WORKING_DIR__/fpp-filenames'
-- INFO  -- Removing: /tmp/__FPP_WORKING_DIR__

**Comment by Joshua-Anderson** [comment]
@sayaplayer96 fpp is a scala binary installed via pip. It looks like we're not publishing binaries for aarch64 systems yet, so we don't have anyprebuilt binaries for your system.

Feel free to build from source in the meantime though! See instructions [here](https://github.com/fprime-community/fpp/tree/main/compiler)

**Comment by sayaplayer96** [comment]
> @sayaplayer96 fpp is a scala binary installed via pip. It looks like we're not publishing binaries for aarch64 systems yet, so we don't have anyprebuilt binaries for your system.
> 
> Feel free to build from source in the meantime though! See instructions [here](https://github.com/fprime-community/fpp/tree/main/compiler)

Thank you, problem solved!

**Comment by yanzixiang** [comment]
@sayaplayer96 can you publish the binarie for aarch64 systems ?
