### ISSUE TITLE
how to use FPP_DOWNLOAD_CACHE ?

### ISSUE THREAD

**Issue by yanzixiang** [fprime-community/fpp#200]
https://github.com/fprime-community/fpp/blob/687fedfc52a1f8e2b55c0f3f5764e1fcade19409/fprime_fpp/fprime_fpp_install.py

""" install.py:
Installs the FPP tool suite based on the version of this installer package. It will use FPP_DOWNLOAD_CACHE environment
variable to pull up previously downloaded items for users that wish to install offline.
"""

i wonder which file should be put in the FPP_DOWNLOAD_CACHE dir ?

**Comment by bocchino** [comment]
@LeStarch Can you comment on this?

**Comment by LeStarch** [comment]
You can download the FPP release tarball and place it in the directory pointed to by FPP_DOWNLOAD_CACHE and it should prevent a redundant download.

**Comment by bocchino** [comment]
Closing this issue as answered.
