### ISSUE TITLE
Fix bugs in generated C++ for ports

### ISSUE THREAD

**Issue by bocchino** [fprime-community/fpp#209]
We need to fix the following bugs in the Python port autocoder:

1. The Python autocoder generates incorrect code in the `invoke` function of the `OutputPort` class. If port serialization is turned on, then there is an access to `m_port` guarded by a check that either `m_port` or `m_serPort` is non-null. In this case, if `m_serPort` is non-null and `m_port` is null, a seg fault occurs.

2. The Python autocoder assumes that `nullptr == 0`, which C++ does not guarantee.

See https://github.com/fprime-community/fpp/pull/208#issuecomment-1385933219.

**Comment by bocchino** [comment]
Note: After we merge #208, this one will become moot.

>The Python autocoder generates incorrect code in the case where an output port with a return type is connected to a serial input port.

**Comment by bocchino** [comment]
> Note: After we merge https://github.com/fprime-community/fpp/pull/208, this one will become moot.

Actually, strike that. It looks like the assertion is wrong even in the case where a typed port is connected to a typed port. It's just that the seg fault doesn't occur in this case.

**Comment by tiffany1618** [comment]
> Note: After we merge #208, this one will become moot.

I think this is correct; the generated code is different for a port without a return type:

https://github.com/fprime-community/fpp/blob/d55f67d48c8fe01994bd1abddd47974e98ab6667/compiler/tools/fpp-to-cpp/test/port/EmptyPortAc.ref.cpp#L141-L158

vs. a port with a return type:

https://github.com/fprime-community/fpp/blob/d55f67d48c8fe01994bd1abddd47974e98ab6667/compiler/tools/fpp-to-cpp/test/port/ReturnTypePortAc.ref.cpp#L110-L115

Maybe we can clean this up a little bit. So, for ports without a return type we would generate something like:

```c++
#if FW_PORT_SERIALIZATION
  FW_ASSERT(this->m_port != nullptr || this->m_serPort != nullptr);

 if (this->m_port != nullptr) {
    this->m_port->invoke();
  } else if (this->m_serPort != nullptr) {
    // Initialize _buffer

    _status = this->m_serPort->invokeSerial(_buffer);
    FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
  }
#else
  FW_ASSERT(this->m_port != nullptr);
  return this->m_port->invoke(u);
#endif
```

And for ports with a return type:

```c++
    FW_ASSERT(this->m_port != nullptr);
    return this->m_port->invoke(u);
```

**Comment by bocchino** [comment]
Yes, this looks good! While we have the opportunity to clean up the formatting, I would put parentheses around the operands to the or operator `||` and move the `else` to a new line.

**Comment by bocchino** [comment]
Also the else if condition is unnecessary, given the assertion. We could simplify the port serialization case to
```
if m_port != nullptr
  invoke m_port
else
  assert m_serPort != nullptr
  invoke m_serPort
```

**Comment by tiffany1618** [comment]
Ok, that sounds good. I'll make those changes, too.
