### ISSUE TITLE
Add optional header file to instance definitions

### ISSUE THREAD

**Issue by bocchino** [fprime-community/fpp#21]
For example, you should be able to say
```
instance foo: Foo base id 0x100 at "../../Bar.hpp"
```
This definition says that `foo` is an instance of the `Foo` component and the C++ header file of its implementation is located at `../../Bar.hpp`.  This construction supports the case where a single component model has several different C++ implementation classes. If no path is given, e.g.,
```
instance foo: Foo base id 0x100
```
then the translator will use a default header file, e.g., `Foo.hpp` (or `FooComponentImpl.hpp` if that more verbose form is desired) in the directory where the `Foo` component model is located.

**Comment by bocchino** [comment]
@LeStarch FYI. This enhancement should support the pattern that we discussed yesterday.

**Comment by LeStarch** [comment]
Understood. Thanks for tracking it.

**Comment by bocchino** [comment]
Done in commit 8cca9c758ce85c1089ac9eff908855282c667fa7.
