### ISSUE TITLE
Implement C++ component base classes

### ISSUE THREAD

**Issue by bocchino** [fprime-community/fpp#215]
Implement C++ code gen for component base classes.

**Comment by tiffany1618** [comment]
- [ ] Hpp file
    - [ ] Component functions (constructor, destructor, etc.)
    - [ ] Input port instance members
    - [ ] Output port instance members
    - [ ] Special port instance members
    - [ ] Internal port instance members
    - [ ] Command members
    - [ ] Event members
    - [ ] Telemetry members
    - [ ] Parameter members
- [ ] Cpp file
    - [ ] Component function implementations
    - [ ] Input port instance function implementations
    - [ ] Output port instance function implementations
    - [ ] Special port instance function implementations
    - [ ] Internal port instance function implementations
    - [ ] Command function implementations
    - [ ] Event function implementations
    - [ ] Telemetry function implementations
    - [ ] Parameter function implementations
