### ISSUE TITLE
Test C++ component base classes

### ISSUE THREAD

**Issue by bocchino** [fprime-community/fpp#216]
Test C++ code gen for component base classes.

**Comment by tiffany1618** [comment]
- [ ] Hpp files compile with cpp files generated by Python autocoder
- [ ] All files compile with F Prime
- [ ] All files pass F Prime unit tests
- [ ] Write comprehensive functional tests for components in F Prime
- [ ] All files pass functional tests for components

**Comment by bocchino** [comment]
Closed as completed in #240.
