### ISSUE TITLE
Test C++ component implementation templates

### ISSUE THREAD

**Issue by bocchino** [fprime-community/fpp#219]
Test C++ code gen for component implementation templates.

**Comment by tiffany1618** [comment]
- [ ] Hpp files compile with cpp files generated by Python autocoder
- [ ] All files compile with F Prime
- [ ] All files pass F Prime unit tests
- [ ] Write comprehensive functional tests for components in F Prime
- [ ] All files pass functional tests for components

**Comment by bocchino** [comment]
Done in #268.
