### ISSUE TITLE
Inconsistent license

### ISSUE THREAD

**Issue by dkogan** [fprime-community/fpp#232]
Your have a LICENSE and NOTICE file in the top level. One claims an Apache license and the other a BSD license. Please clarify.

**Comment by bocchino** [comment]
I don't see any inconsistency. There is an Apache license in LICENSE.txt. There is also a NOTICE.txt file as provided in section 4(d) of the license.

**Comment by dkogan** [comment]
The NOTICE file contains the text of a BSD license, which confusing at best. That section of the text states that if you include a NOTICE (which is optional) then it contains the copyrights, not the licensing terms. The apache people have a sample NOTICE file here: https://infra.apache.org/licensing-howto.html that represents the intent
