### ISSUE TITLE
Make FPP Component Autocoder Mark init as public

### ISSUE THREAD

**Issue by LeStarch** [fprime-community/fpp#238]
In the python autocoder we needed to make `init` on the component base class `public` so users did not need to implement it themselves.

See:
https://github.com/nasa/fprime/pull/1950

**Comment by bocchino** [comment]
@tiffany1618 We need to make the FPP component code gen correspond to this change in the Python autocoder. It looks like a small change. Let us know if you have any questions.

**Comment by tiffany1618** [comment]
@LeStarch @bocchino Ok, this has been changed in commit 0d1661b.

**Comment by bocchino** [comment]
Looks good! I'm closing this issue as addressed in #240.
