### ISSUE TITLE
Add static assertions for dependent F Prime flags

### ISSUE THREAD

**Issue by tiffany1618** [fprime-community/fpp#303]
Some combinations of settings of F Prime flags will cause the generated code to fail to compile. To assist the user, we should add static assertions that check for these conditions and provide clear error messages. 

Known dependencies:

- If `BUILD_UT` is on, `FW_SERIALIZABLE_TO_STRING` and `FW_ARRAY_TO_STRING` must also be on
-  `FW_SERIALIZABLE_TO_STRING` and `FW_ARRAY_TO_STRING` are dependent in the following cases:
   - If an array containing structs is defined and `FW_ARRAY_TO_STRING` is on, then `FW_SERIALIZABLE_TO_STRING` must also be on
   - If a struct containing arrays is defined and `FW_SERIALIZABLE_TO_STRING` is on, then `FW_ARRAY_TO_STRING` must also be on

**Comment by bocchino** [comment]
It would be good to eliminate `FW_ARRAY_TO_STRING` and replace all of its uses with `FW_SERIALIZABLE_TO_STRING`. This is already what we do for enums.

**Comment by bocchino** [comment]
We could also add more "... or defined BUILD_UT" conditions to try to cover the cases, but to me this seems error-prone. I think the approach described in this issue is more systematic and robust. For unit testing, we need these strings, so we should just specify and check the invariant.

**Comment by bocchino** [comment]
> We could also add more "... or defined BUILD_UT" conditions to try to cover the cases as suggested in https://github.com/fprime-community/fpp/issues/369, but to me this seems error-prone.

To me the issue is (1) a lot of unit test code is written assuming that we have string representations of the data and (2) there's no easy way to find all these assumptions and guard them with "... or defined BUILD_UT." In fact, I think we were trying to do this about a year and a half ago and decided that it's too brittle.

**Comment by bocchino** [comment]
Also, when we wrestled with this issue about a year and a half ago, we saw that code can say
```
#if FW_SERIALIZABLE_TO_STIRING or defined BUILD_UT
[ code ]
#endif
```
where [ code ] really needs SERIALIZABLE_TO_STRING to be enabled, so with BUILD_UT on and SERIALIZABLE_TO_STRING off, the compilation breaks. The approach discussed in this issue avoids that problem. I remember we specifically decided to avoid the pattern `#if X or BUILD_UT`, and instead insist that X is on when BUILD_UT is on.

**Comment by bocchino** [comment]
Moved this issue to https://github.com/nasa/fprime/issues/2467.
