### ISSUE TITLE
[Dp component code gen] Handle missing elements

### ISSUE THREAD

**Issue by bocchino** [fprime-community/fpp#339]
Make sure that analysis and C++ code gen works correctly in the following cases:
* Product ports but no records or containers
* Containers but no records (will exclude from model)
* Records but no containers (will exclude from model)

This was an annoyance in the old XML-to-C++ autocoder: things would randomly fail to compile or link if all the standard elements were not present.

**Comment by timcanham** [comment]
@bocchino I think that those conditions should fail in the model, since they are all needed.

**Comment by bocchino** [comment]
OK. For now I am following the pattern inherited from XML for commands, etc., where it's allowed to have command ports but no commands. We can rethink this, but I think we should be consistent across the entire ground interface.

Also, sometimes it's useful to start developing an FPP model and put in command ports but no commands. Eventually you need all these things, but if you require them all, then you disallow that stage of development.

**Comment by bocchino** [comment]
A middle ground position could be that if you have records you need containers and vice versa (and you need the DP ports) but you can have one or more of the DP ports without the containers and records. That would be consistent with the way that commands, etc. currently work.

**Comment by bocchino** [comment]
For now I'll go ahead and implement that middle ground position. It will require a change to the spec, localized to data products.

**Comment by bocchino** [comment]
This strategy also makes testing easier, because it removes valid combinations from the C++ output.

**Comment by bocchino** [comment]
I'll open a separate issue on whether special ports for X should be allowed when X is not defined (X = commands, telemetry, etc.).

**Comment by bocchino** [comment]
Done in commit 2ac2abde0c31c5553de8210e4106d62ccfbd2f34.
