### ISSUE TITLE
python3 is missing from Linux native build environment

### ISSUE THREAD

**Issue by bocchino** [fprime-community/fpp#373]
This causes a build failure, since the native build runs the unit tests, and the unit tests invoke python3. See https://github.com/fprime-community/fpp/pull/372#issuecomment-1875738802.

For now I worked around the issue by skipping the check if python3 is not available https://github.com/fprime-community/fpp/blob/b53c665ba02edb5ee8bcd3c96e48909dabb1408d/compiler/tools/fpp-to-json/test/run#L27-L34. We should fix the underlying issue if possible.

**Comment by LeStarch** [comment]
Work around is appropriate given the context.  If this becomes a generic error, we can get python3 in there.

**Comment by bocchino** [comment]
Agreed.

**Comment by bocchino** [comment]
Note: The environment has no python3 because it is old. It is old so that the build can support older systems.
