### ISSUE TITLE
ComponentTester.cpp from-port handlers not implemented

### ISSUE THREAD

**Issue by thomas-bc** [fprime-community/fpp#397]
We have seen reports of an issue (https://github.com/fprime-community/fprime-tutorial-math-component/issues/26) in the MathComponent tutorial where the handler for `Tester::from_mathOpOut_handler()` is still marked as TODO after following the tutorial. 

After some investigation, I have found that the Python autocoders used to implement that handler

```
  void Tester ::
    from_mathOpOut_handler(
        const NATIVE_INT_TYPE portNum,
        F32 val1,
        const MathModule::MathOp &op,
        F32 val2
    )
  {
    this->pushFromPortEntry_mathOpOut(val1, op, val2);
  }
```

Where fpp-to-cpp autocodes 

```
  void Tester ::
    from_mathOpOut_handler(
        const NATIVE_INT_TYPE portNum,
        F32 val1,
        const MathModule::MathOp &op,
        F32 val2
    )
  {
    // TODO
  }
```

Is this something we can get fpp-to-cpp to do as well?

**Comment by bocchino** [comment]
Yes, we should fix this. Also, we should get that code out of the user-edited template and into the auto-generated code.
